name: API Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Newman
      run: npm install -g newman newman-reporter-htmlextra

    - name: Run Tests
      run: run: newman run "Desafio Automacao API.postman_collection.json" -r htmlextra --env-var baseUrl=https://serverest.dev --reporter-htmlextra-export report.html

    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: API-Test-Report
        path: report.html













































































































































      
